---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.80.10 
    jenkins-agent-01:
      ansible_host: 51.250.66.103
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user
