apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-clien

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-multitool-app
  template:
    metadata:
      labels:
        app: nfs-multitool-app
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        command: [ "/bin/sh", "-c", "while true; do echo 'hello' >> /data/hello.txt; sleep 5; done" ]
        volumeMounts:
          - mountPath: /data
            name: nfs-data
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfs-pvc
