apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
automountServiceAccountToken: true
