---

- name: Install nginx
  hosts: lighthouse-01
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: sudo systemctl restart nginx
  tasks:
    - name: Install EPEL repo 
      ansible.builtin.yum:
        name: epel-release
        state: present
      become: yes
    - name: NGINX | Install nginx 
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: NGINX | Create general config
      become: true
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: reload-nginx

- name: Install Lighthouse
  hosts: lighthouse-01
  handlers:
    - name: reload-nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | Install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: Lighthouse | Copy from git
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ Lighthouse_location_dir }}"
   - name: Lighthouse | Create Lighthouse config
     become: true
     template:
       src: lighthouse.conf.j2
       dest: /etc/nginx/conf.d/default.conf
       mode: 0644
     notify: reload-nginx

- name: Install Clickhouse
  hosts: clickhouse-01
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-client-{{ clickhouse_version }}.noarch.rpm"
        dest: "/tmp/clickhouse-client-{{ clickhouse_version }}.rpm"
        mode: '0644'
      # Скачивание основных пакетов в /tmp для установки
    - name: Get clickhouse common static distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        dest: "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"
        mode: '0644'
    - name: Get clickhouse server distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-server-{{ clickhouse_version }}.noarch.rpm"
        dest: "/tmp/clickhouse-server-{{ clickhouse_version }}.rpm"
        mode: '0644'
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name: 
          - "/tmp/clickhouse-common-static-{{ clickhouse_version }}.rpm"
          - "/tmp/clickhouse-client-{{ clickhouse_version }}.rpm"
          - "/tmp/clickhouse-server-{{ clickhouse_version }}.rpm"
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install and Configure Vector
  hosts: vector-01
  become: true
  tasks:
    - name: Download Vector Distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
        mode: '0644'

    - name: Install Vector
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}.rpm"
        state: present

    - name: Deploy Vector Configuration
      ansible.builtin.template:
        src: templates/vector.toml.j2
        dest: /etc/vector/vector.toml
        mode: '0644'
      notify: Restart Vector

  handlers:
    - name: Restart Vector
      ansible.builtin.service:
        name: vector
        state: restarted
